### ISSUE TITLE
slapd failing

### ISSUE THREAD

**Issue by nblumoe** [cema-sp/iredmail-docker#3]
I encountered an issue with slapd during docker build:

```
Setting up slapd (2.4.31-2) ...
  Creating new user openldap... done.
  Creating initial configuration... done.                                          
  Creating LDAP directory... done.                                                 
Starting OpenLDAP: slapd failed!                                                   
invoke-rc.d: initscript slapd, action "start" failed.                              
dpkg: error processing slapd (--configure):                                        
 subprocess installed post-installation script returned error exit status 1       
```

**Comment by nblumoe** [comment]
This can be prevented by removing https://github.com/cema-sp/iredmail-docker/blob/master/Dockerfile.example#L88
But of course then the services are not started. I am trying to find out, why slapd does not start.

**Comment by nblumoe** [comment]
Starting slapd with `-d 5000` revealed a ch_malloc error. After adding a swap partition to my host machine (Digital Ocean 512MB instance), it seems to be working now. So I am closing this issues.

**Comment by nblumoe** [comment]
@cema-sp slapd consumes >350MB on my installation even though I have only very little data (few kB) in the DBs. Any idea what might be wrong? I fiddled with the cachesize and thread parameters in slapd.conf without any luck ;(

**Comment by cema-sp** [comment]
@nblumoe 
1. I should try to build image without https://github.com/cema-sp/iredmail-docker/blob/master/Dockerfile.example#L88 line, It is not the best way as I think;
2. I will add swap partition requirement to README file;
3. On my server with ~20 users slapd uses 710Mb VIRT (170 RES). Please refer this [Docker issue](https://github.com/docker/docker/issues/8231). You could try setting `ulimit -n 1024` for slapd somehow.

**Comment by nblumoe** [comment]
@cema-sp 
1. without Line 88 the error does not occur, but iRedMail also does not install correctly. So we should keep this I think.
2. Not sure if a swap partition is really needed. I suspect this just happened because more memory was available.
3. I simply did `ulimit -n 1024` on the running container and now slapd is down to ~20MB. I would expect it to be enough to add that to the Dockerfile.

**Comment by cema-sp** [comment]
@nblumoe 
I agree about memory allocation. I also tried `ulimit -n 1024` config and now slapd uses VIRT=270Mb and RES=50Mb, great progress.
