### ISSUE TITLE
cannot move `./mail_users.csv.ldif' to `ldifs/20_mail_users.ldif'

### ISSUE THREAD

**Issue by kopax** [cema-sp/iredmail-docker#8]
Trying to build without touching any files :

```
mv: cannot move `./mail_users.csv.ldif' to `ldifs/20_mail_users.ldif': No such file or directory
```

Looks the image on docker hub `cema/iredmail:example` is different from this one.

It will crash on this line also 

```
RUN cp /opt/iredmail/conf/ldap_init.ldif ldifs/00_ldap_init.ldif \
```

By commenting these lines dockerfile, there is still this error :

```
 ldap_bind: Invalid credentials (49)
```

Is it possible to have access to the source of the builded image tagged example in docker hub ?

**Comment by cema-sp** [comment]
Please see issue #3 and fix: 4110de21aaeef252b4e46ef238e94bac75f52804
